l1=[]
l2=[]
iller = "ADANAADIYAMANAFYONKARAHİSARAĞRIAKSARAYAMASYAANKARAANTALYAARDAHANARTVİNAYDINBALIKESİRBARTINBATMANBAYBURTBİLECİKBİNGÖLBİTLİSBOLUBURDURBURSAÇANAKKALEÇANKIRIÇORUMDENİZLİDİYARBAKIRDÜZCEEDİRNEELAZIĞERZİNCANERZURUMESKİŞEHİRGAZİANTEPGİRESUNGÜMÜŞHANEHAKKARİHATAYIĞDIRISPARTAİSTANBULİZMİRKAHRAMANMARAŞKARABÜKKARAMANKARSKASTAMONUKAYSERİKIRIKKALEKIRKLARELİKIRŞEHİRKİLİSKOCAELİKONYAKÜTAHYAMALATYAMANİSAMARDİNMERSİNMUĞLAMUŞNEVŞEHİRNİĞDEORDUOSMANİYERİZESAKARYASAMSUNSİİRTSİNOPSİVASŞANLIURFAŞIRNAKTEKİRDAĞTOKATTRABZONTUNCELİUŞAKVANYALOVAYOZGATZONGULDAK"
sayac = ""
for harf in iller:
    if harf not in sayac:
        sayac += harf
for harf in sayac:
    l1.append(harf)
    l2.append(int(iller.count(harf)))
def sirala(elem):
    return elem[1]
liste3=[[e1,e2] for e1,e2 in zip(l1,l2)]
liste3.sort(key=sirala)
print(liste3)